"""add cn appraisals ev bonus cols gerente appraisals

Revision ID: 9d8a108b4890
Revises: ec93b8ba8be3
Create Date: 2026-04-10 16:58:46.670943

"""
from alembic import op
import sqlalchemy as sa
from app.models.compat import GUID


# revision identifiers, used by Alembic.
revision = '9d8a108b4890'
down_revision = 'ec93b8ba8be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cn_monthly_appraisals',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('cn_id', GUID(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sao_realizado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vidas_realizado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pct_sao', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('pct_vidas', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('score_final', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('multiplicador', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cn_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cn_id', 'month', 'year', name='uq_cn_monthly_appraisal')
    )
    op.create_table('gerente_quarter_appraisals',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('gerente_id', GUID(length=36), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('meta_mrr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('meta_sql', sa.Integer(), nullable=False),
    sa.Column('realizado_mrr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realizado_sql', sa.Integer(), nullable=False),
    sa.Column('pct_mrr', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('pct_sql', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('multiplicador', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gerente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gerente_id', 'quarter', 'year', name='uq_gerente_quarter_appraisal')
    )
    with op.batch_alter_table('ev_quarter_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('salario_base_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ev_quarter_achievements', schema=None) as batch_op:
        batch_op.drop_column('salario_base_snapshot')
        batch_op.drop_column('bonus_amount')

    op.drop_table('gerente_quarter_appraisals')
    op.drop_table('cn_monthly_appraisals')
    # ### end Alembic commands ###
