"""add initial_installments_paid

Revision ID: bed5f7ad4ac0
Revises: 
Create Date: 2026-04-02 15:23:05.305236

"""
from alembic import op
import sqlalchemy as sa
from app.models.compat import GUID


# revision identifiers, used by Alembic.
revision = 'bed5f7ad4ac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ev_quarter_achievements',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('ev_id', GUID(length=36), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_mrr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mrr_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('achievement_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ev_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ev_id', 'quarter', 'year', name='uq_ev_quarter_achievement')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_installments_paid', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('initial_installments_paid')

    op.drop_table('ev_quarter_achievements')
    # ### end Alembic commands ###
