"""add cn profile fields and cn monthly goals

Revision ID: ec93b8ba8be3
Revises: 5fd44aa9a820
Create Date: 2026-04-10 16:42:22.055544

"""
from alembic import op
import sqlalchemy as sa
from app.models.compat import GUID


# revision identifiers, used by Alembic.
revision = 'ec93b8ba8be3'
down_revision = '5fd44aa9a820'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    # Create enum types for PostgreSQL (SQLite doesn't support native ENUMs)
    if dialect == 'postgresql':
        op.execute("CREATE TYPE cn_nivel AS ENUM ('CN1', 'CN2', 'CN3')")
        op.execute("CREATE TYPE cn_porte AS ENUM ('M', 'G+')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cn_monthly_goals',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('cn_id', GUID(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sao_target', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vidas_target', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cn_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cn_id', 'month', 'year', name='uq_cn_monthly_goal')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.Enum('CN1', 'CN2', 'CN3', name='cn_nivel'), nullable=True))
        batch_op.add_column(sa.Column('porte', sa.Enum('M', 'G+', name='cn_porte'), nullable=True))
        batch_op.add_column(sa.Column('salario_base', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salario_base')
        batch_op.drop_column('porte')
        batch_op.drop_column('nivel')

    op.drop_table('cn_monthly_goals')
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("DROP TYPE IF EXISTS cn_nivel")
        op.execute("DROP TYPE IF EXISTS cn_porte")
    # ### end Alembic commands ###
